### ISSUE TITLE
Search for a Meeting Room

### ISSUE THREAD

**Issue by lianilychee** [APL-Innovation-Lab/meeting-room#23]
### Description

As a visitor to the Austin Public Library website,
I want to be able to find a room that fits my criteria,
So that I can book a room that works for me during a time that works for me. 

#### Scenario: Viewing the Landing Page

- Given I am a visitor to the Austin Public Library website
- When I select a "Reserve Online" option from the "Meeting Spaces" page
- Then I'm navigated to the "Find a Room" page
- And I can see a prominent title "Find a Room" and a descriptive paragraph outlining purpose of the selected "Reserve Online" option from the previous page
- And I can see breadcrumbs at the top of the page to navigate me back to the "Meeting Spaces" page or the "Home" page

### Attachments
- [Link to design mockup (business)](https://www.figma.com/design/DMjN6uhMLOw7VZO3t4eqjd/APL-Meeting-Room?node-id=744-91235&t=mGF3fqrKC518cZcG-4)
- [Link to design mockup (non-commercial)](https://www.figma.com/design/DMjN6uhMLOw7VZO3t4eqjd/APL-Meeting-Room?node-id=744-91137&t=mGF3fqrKC518cZcG-4)

### Notes
* This is the part of the mock that the ticket is about:
* <img width="408" alt="Screenshot 2024-07-31 at 6 28 07 PM" src="https://github.com/user-attachments/assets/bd264687-05bd-40c7-97ca-e9631bec3b3b">

### Implementation details
1. Reuse header from USWDS.  Need semantic HTML tags

**Comment by julielaursen** [comment]
For non-business flow, I do not see any booking constraints specifically called out in the header (ex 2 weeks out etc). Is that because we're deciding policy placement still?
Is showing available listed top down by locations with the most availability?
What text or image should display when there are no locations available

**Comment by tjdev7** [comment]
Working on this now. Just making this comment to let the rest of the contributors inside this repo know.

**Comment by tjdev7** [comment]
I'm almost done with this task. Only things missing are:

- [ ] Integrate all of the fonts from the Figma file so they share the same UI design (adding the Source Sans Pro and Inter to the project or anything other font similar)
- [ ] Adding arrow Icon that indicate where a user is currently in (these symbols > for when a user progresses in the app)


Will be making more updates for it soon.

![Image](https://github.com/user-attachments/assets/c671bd83-72f1-411c-89dc-dfb5921b83c9)

![Image](https://github.com/user-attachments/assets/06c8197d-5efc-4e09-9492-e7b42bcf00d5)

**Comment by tjdev7** [comment]
I'm almost done with my commit. I just need to resolve one error that's currently popping up in my terminal. It's in regards to some components that are already inside the forked repo.

![semi final - search for room commecial](https://github.com/user-attachments/assets/2aeaf2ce-50af-449c-8f2e-9e0f838410f7)
![semi final - search for room Non commecial](https://github.com/user-attachments/assets/5cd38c53-a5e8-4ca3-bd62-822a03de5a09)
![Screenshot 2024-09-05 at 6 37 24 PM](https://github.com/user-attachments/assets/b55f2abe-83f5-4e92-9624-45d7590cf6f6)
![SearchRoom Error code -  Breadcrumbs issue](https://github.com/user-attachments/assets/bb0b9f05-583e-4e84-ac19-fbab577bfa2f)

**Comment by tjdev7** [comment]
Just finished with my task now. Pushing my PR to GitHub in a few minutes with no error messages inside of it. 

![Search for room - commercial Finale](https://github.com/user-attachments/assets/9145df65-b89f-4939-9047-3b496701d038)
![Search for room - Non commercial Finale](https://github.com/user-attachments/assets/7fefa7a4-edc3-4d52-af51-dd4810233679)
